### ISSUE TITLE
Stream URL

### ISSUE THREAD

**Issue by odehalaa** [dnhen/vidgrid#1]
Hi,

I need to thank you for your amazing app,

I need to ask you if possible to add any source of streams or only support YouTube ?

and can we add more than10 channels ?

Best Regards

**Comment by dnhen** [comment]
Hey @odehalaa ,

Thanks for the kind words.

Absolutely; currently, the streams that are supported are as follows:
- YouTube;
- Facebook;
- SoundCloud;
- Streamable;
- Vimeo;
- Wistia;
- Twitch;
- DailyMotion;
- Vidyard;
- HLS and DASH streams;
- Any streamable file type.

If you have any specific file you want to play (or URL), feel free to send it through so I can add support.

With regards to adding more than 10 channels, that is possible. How many channels were you thinking?

Thanks in advance.

**Comment by odehalaa** [comment]
Dear Dnhen,

 

Thank you very much for your generous support.

I currently have a URL containing HTTP HLS streams and would appreciate your assistance in enabling support for UDP multicast for local network streams. Additionally, I am interested in the possibility of extending support for more than 10 channels to support 16 and 20 channels, if feasible.

 

https://github.com/iptv-org/iptv/blob/master/streams/qa.m3u

 

sample source of multicast stream from local network and working on vlc

 

***@***.***:49000

 

Best Regards,

 

Alaa Odeh



Sent: Tuesday, December 19, 2023 at 3:41 PM

**Comment by dnhen** [comment]
@odehalaa ,

I have added the ability to display a grid of 16 and 20 channels. Hopefully this allows you to view more videos at once.

With regards to the UDP multicast streaming; this is going to take even more time. Apologies for not being able to provide this straight away. I'll keep working on it and if I get any success, I'll let you know.

Thanks.

**Comment by odehalaa** [comment]
Dear Denhe,

I want to express my sincere gratitude for your dedicated efforts in supporting 16 and 20 channels. Additionally, I hope to see support for UDP multicast stream in the future updates. If possible, could you also provide documentation on how to install it on a local machine?

Thank you.

Best regards,


 

Sent: Thursday, December 28, 2023 at 11:40 AM
